### ISSUE TITLE
Community Detection

### ISSUE THREAD

**Issue by timeskub** [snap-stanford/snap-python#107]
I am trying to use community detection algos available in SNAP.

I got the Error " RuntimeError: Execution stopped: (0<=ValN)&&(ValN<Vals) [Reason:'Index:-2147275013 Vals:1073853485 MxVals:1162127360 Type:TVec<class TTriple<class TFlt,class TInt,class TInt>,int>'], file S:\glib-core\ds.h, line 491".

What can be possible reasons for this? How to deal with this issue?

```
G = snap.LoadEdgeList(snap.PUNGraph, "./dataset/com-youtube.ungraph.txt", 0, 1)
CmtyV = snap.TCnComV()
modularity = snap.CommunityCNM(G, CmtyV)
```

**Comment by roks** [comment]
I suspect that your graph is too large for the method, this method does not scale well to large graphs.
