### ISSUE TITLE
Pip Install Fails for Python 3.8

### ISSUE THREAD

**Issue by ChasNelson1990** [snap-stanford/snap-python#121]
Trying to install snap for python on Arch Linux with Python 3.8 using pip and I get:

```
ERROR: Could not find a version that satisfies the requirement snap-stanford (from versions: none)
ERROR: No matching distribution found for snap-stanford
```

Am I correct in assuming this means that no binaries have ever been pushed to pypi for py3.8? Is this on your roadmap at all?

**Comment by ChasNelson1990** [comment]
Note that I think this is different to #111 or #120, hence the new issue.

**Comment by roks** [comment]
Yes, you are correct. We have not yet prepared a py3.8 release. We plan to create this release within the next couple of months.

**Comment by dheeman00** [comment]
So what is the best way to install previous versions using pip?

**Comment by roks** [comment]
Please see the following document for supported versions: https://docs.google.com/spreadsheets/d/1m-5gHUmGzh8XfLUCAY3eYvdcBA98TUMMusVZkwmpdaI/edit#gid=0
