### ISSUE TITLE
SaveSS(OutFNm) -- SegFault

### ISSUE THREAD

**Issue by hcars** [snap-stanford/snap-python#133]
My code segfaults when running the following,
```

context = snap.TTableContext()
table = snap.TTable.GetEdgeTable(network, context)
f_out = snap.TFOut(outputTsvFile) # outputTsvFile is a string filename
table.SaveSS(f_out)
f_out.Flush()
```
This works fine when I replace `SaveSS` with`Save`, and `SaveSS` seems to have trouble in other contexts as well. Is this me misusing the method, or is there something wrong with the implementation?

**Comment by ameya98** [comment]
Based on the example in the reference: http://snap.stanford.edu/snappy/doc/reference/table.html
you should be using `Save()`:
```Python
outfile = "/path/to/output.bin"
FOut = snap.TFOut(outfile)
table.Save(FOut)
FOut.Flush()
```
