### ISSUE TITLE
How to install snap for arm architecture on Ubuntu 18

### ISSUE THREAD

**Issue by mink007** [snap-stanford/snap-python#152]
when i try to 'make', the make does not go beyond these lines

*************
make -C swig
make[1]: Entering directory '/home/spartans/CS224W/hw0-bundle/snap-python/swig'
swig -D_CMPWARN -D__stdcall -DSW_SNAPPY -D_OPENMP -DNONUMPY -DUSE_OPENMP -DGCC_ATOMIC -python -c++ -w302,312,317,325,362,383,384,389,401,503,508,509 -O -I../../snap/snap-core -I../../snap/glib-core snap.i

*************

**Comment by roks** [comment]
swig might take some time to complete. Make sure that SNAP_ALL is set to 0 in swig/snap.i to speed up the development.

**Comment by mink007** [comment]
i will try again with SNAP_ALL set to 1 and see how long it takes to install. 
Thank you for your response.  

I am installing on Jetson AGX Xavier
