### ISSUE TITLE
Snap crashes IPython on OSX 10.9.5 Anaconda Install

### ISSUE THREAD

**Issue by andrewverte** [snap-stanford/snap-python#46]
Hi,

I'm trying to use Snap with IPython on OSX 10.9.5 with Anaconda Python v. 3.8.1. However, I keep getting a fatal crash.

(gl)Andrews-MacBook-Pro:~ ag$ ipython qtconsole --pylab=inline
QPixmap::scaled: Pixmap is a null pixmap
Fatal Python error: PyThreadState_Get: no current thread

Snap imports correctly in IPython when not using qtconsole.

Do you have any advice?

Thanks,
Andrew

**Comment by rob-p** [comment]
I'm getting a related error on OSX 10.10.4 with python 2.7.8
```
Python 2.7.8 (default, Oct 19 2014, 16:02:00)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.append("swig")
>>> import snap
Fatal Python error: PyThreadState_Get: no current thread
[1]    12991 abort      python
```

Any idea what could be going wrong here?

**Comment by charlescearl** [comment]
I was able to get this working in on OSX 10.10.2 with conda 3.16.0 by making a change in the supplied 
setup.py, line 130:
129 if uname[0] == "Darwin":
130    dynlib_path = getdynpath()

By setting dynlib_path to the path of CONDA_PATH/lib/libpython2.7.dylib, e.g.
130   dynlib_path = CONDA_PATH/lib/libpython2.7.dylib

where CONDA_PATH is the path to your anaconda installation, e.g.
CONDA_PATH = //anaconda

I have not looked deeply into why the getdynpath() is not working for my installation, but looks like it could be fixed easily.

**Comment by cxhernandez** [comment]
@charlescearl is right. It turns out that `getdynpath()` in `setup.py` does a poor job of finding `libpython2.7.dylib` in Anaconda Python environments.
