### ISSUE TITLE
snap.GenRMat is not a thing in my installation of snap on Mac OS?

### ISSUE THREAD

**Issue by abitofalchemy** [snap-stanford/snap-python#60]
On a Mac OS system I try to use `snap.GenRMat` and I get an error. I did do `brew install swig` and even with that package/module installed I get the error (see below).  Clearly I must be doing something **wrong** since I don't see evidence that others are having the same issue. What should I do?

```
>>> import snap
>>> P = [[.9124,.5884],[.5029,.2165]]
>>> sum = .9124+.5884+.5029+.2165 #enron
>>> num_nodes=6; num_edges=8
>>> GRmatSNAP = snap.GenRMat(num_nodes, num_edges, P[0][0]/sum, P[0][1]/sum, P[1][0]/sum)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'GenRMat'
```

**Comment by roks** [comment]
The code works on my machine. Make sure that there are no other 'snap' modules on the system.
