### ISSUE TITLE
undefined symbol error when trying to load snap on either centos-7 or Ubuntu 15.04

### ISSUE THREAD

**Issue by akulakov** [snap-stanford/snap-python#61]
After making snap-python, I get this error:

>>> import sys;sys.path.append('swig')
>>> import snap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "swig/snap.py", line 30, in <module>
    _snap = swig_import_helper()
  File "swig/snap.py", line 26, in swig_import_helper
    _mod = imp.load_module('_snap', fp, pathname, description)
ImportError: swig/_snap.so: undefined symbol: _ZNK7TDirNet5GetEIERKi

**Comment by roks** [comment]
Fixed.

**Comment by SamTube405** [comment]
I'm experiencing the same problem in centos 5.8, is this problem fixed over specific os dists?
