### ISSUE TITLE
ld: symbols not found when compiling on OS X Yosemite

### ISSUE THREAD

**Issue by akulakov** [snap-stanford/snap-python#62]
The full error is as follows:

% make                                                                                 --INS--
make -C swig
g++  -lpython -dynamiclib -headerpad_max_install_names -o _snap.so snap_wrap.o Snap.o cliques.o agm.o agmfast.o agmfit.o
Undefined symbols for architecture x86_64:
  "TDirNet::GetEI(int const&) const", referenced from:
      _wrap_TDirNet_GetEI(_object*, _object*) in snap_wrap.o
     (maybe you meant: __ZNK7TDirNet5GetEIERKiS1_)
  "TUndirNet::GetEI(int const&) const", referenced from:
      _wrap_TUndirNet_GetEI(_object*, _object*) in snap_wrap.o
     (maybe you meant: __ZNK9TUndirNet5GetEIERKiS1_)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [_snap.so] Error 1
make: *** [swig] Error 2

thanks!

**Comment by roks** [comment]
Fixed.
