### ISSUE TITLE
TNEANet.Nodes() method does not exist in Snap.py

### ISSUE THREAD

**Issue by danrozenberg** [snap-stanford/snap-python#67]
Hello, I am using Snap.py version 1.2 \
I have not seen this issue anywhere else on Github, but I did find it in the Google groups. So I decided to open an issue here as well.

Contrary to what the manual states, TNEANet does not have the Nodes() method. It will fail if called and using `dir` does not show the method at all, so something does seem wrong...

**Comment by danrozenberg** [comment]
The same appears to be true for `Edges()`

**Comment by jbarrow** [comment]
The same is true for TUNGraph.

**Comment by roks** [comment]
The following program works OK:
```
import snap
N1 = snap.TNEANet.New()
N1.AddNode(1)
N1.AddNode(5)
N1.AddNode(32)
N1.AddEdge(1,5)
N1.AddEdge(5,1)
N1.AddEdge(5,32)
for NI in N1.Nodes():
    print "node id %d with out-degree %d and in-degree %d" % (
        NI.GetId(), NI.GetOutDeg(), NI.GetInDeg())
```
