### ISSUE TITLE
'module' object has no attribute 'TRnd_LoadXml'

### ISSUE THREAD

**Issue by fighting41love** [snap-stanford/snap-python#73]
When I try to import snap， the following error occurs.

> > > import snap
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/anaconda/lib/python2.7/site-packages/snap.py", line 7868, in <module>
> > >     TRnd.LoadXml = new_instancemethod(_snap.TRnd_LoadXml,None,TRnd)
> > > AttributeError: 'module' object has no attribute 'TRnd_LoadXml'

**Comment by Sophiaaaa** [comment]
Check the source files in the import libraries  and make sure the source file exists and has no error. There is a file named snap.pyc . Delete it and it will runs well.

**Comment by Yili0616** [comment]
Is it solved now? Because I have a similar issue. When I run snap.GenRndGnm, it says that 'module' object has no attribute GenRndGnm...

**Comment by roks** [comment]
The following code works fine in our tests:
```
import snap
G1 = snap.GenRndGnm(snap.PNGraph, 10, 60)
```
