### ISSUE TITLE
GetClosenessCentr Malfunction

### ISSUE THREAD

**Issue by ZacheryPD** [snap-stanford/snap-python#75]
I have been reviewing the documentation [here](https://snap.stanford.edu/snappy/doc/reference/GetClosenessCentr.html?highlight=getclosenesscentr) and of the three examples on that page, the only one I can get to work with Python2.7 is the second one.  Unfortunately, I need this method to work on a directed graph...  Is anyone else seeing this same problem?

**Comment by roks** [comment]
What is the problem? The example in the manual works fine.

**Comment by ZacheryPD** [comment]
I think this may have been some kind of a hiccup in my install of snap.py!  After re-installing, all is well =)
