### ISSUE TITLE
'module' object has no attribute 'trnd'

### ISSUE THREAD

**Issue by Sophiaaaa** [snap-stanford/snap-python#76]
When I try to import snap, the following issue occurs.
      1 import snap
----> 2 Rnd = snap.trnd()
      3 UGraph = snap.GenPrefAttach(500,1,Rnd)
      4 snap.DrawGViz(UGraph,snap.gvlSfdp,"graph_generation_exp.png","BA network",False)
      5 snap.PlotInDegDistr(UGraph,"Degree_distribution","Degree distribution(BA network)")

AttributeError: 'module' object has no attribute 'trnd'

**Comment by viswajithiii** [comment]
I think you're looking for snap.TRnd, not snap.trnd.
