### ISSUE TITLE
name 'snap' is not defined

### ISSUE THREAD

**Issue by Sophiaaaa** [snap-stanford/snap-python#82]
When I draw the UGraph network by the  open source tool called DrawGViz in the layout  of glvCirco:
`snap.DrawGViz(UGraph,snap.gvlCirco,"WS.png","WS small world",False)`

The results shows:

> 
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-cff1afae7314> in <module>()
----> 1 snap.DrawGViz(UGraph,snap.gvlCirco,"WS.png","WS small world",False)

NameError: name 'snap' is not defined

Pls help. Thx.

**Comment by roks** [comment]
Please post a short program that will allow us to replicate the problem.
