### ISSUE TITLE
global name 'PNEANetMP' is not defined

### ISSUE THREAD

**Issue by Sophiaaaa** [snap-stanford/snap-python#83]
> the code is :

`nap.DrawGViz(UGraph,snap.gvlCirco,"WS.png","WS small world",False)`

> and the results shows:

 NameError                                                     Traceback (most recent call last)
<ipython-input-13-cff1afae7314> in <module>()
----> 1 snap.DrawGViz(UGraph,snap.gvlCirco,"WS.png","WS small world",False)

C:\Users\julia\Anaconda2\lib\site-packages\snap.pyc in DrawGViz(tspec, *args)
 208718     if type(tspec) == PNGraph : return DrawGViz_PNGraph(tspec, *args)
 208719     if type(tspec) == PNEANet : return DrawGViz_PNEANet(tspec, *args)
---->208720     if type(tspec) == PNEANetMP : return DrawGViz_PNEANetMP(tspec, *args)
 208721     if type(tspec) == PNGraphMP: return DrawGViz_PNGraphMP(tspec, *args)
 208722     raise TypeError('First argument has invalid type')

NameError: global name 'PNEANetMP' is not defined

> I don't know if there is any problem in the setup files. Pls help. Thx a lot.

**Comment by roks** [comment]
Which OS and Snap.py package do you use? Please also provide a short program that will allow us to replicate the problem.

**Comment by Sophiaaaa** [comment]
>here is the program:

`import snap`
`Rnd = snap.TRnd(1,0)`
`N = int(raw_input('enter the value of N '))`
`k = int(raw_input('enter the value of k '))`
`p = int(raw_input('enter the value of p '))`
`UGraph = snap.GenSmallWorld(N,k,p,Rnd)`
`UGraph = type(raw_input('enter the value of Graph '))`
`snap.DrawGViz(UGraph,snap.gvlCirco,"WS.png","WS small world",False)`
`GraphClustCoeff = snap.GetClustCf(UGraph,-1)`

>and the results is following:

enter the value of N 20
enter the value of k 2
enter the value of p 0
enter the value of Graph network
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-ebaed5996025> in <module>()
      6 UGraph = snap.GenSmallWorld(N,k,p,Rnd)
      7 UGraph = type(raw_input('enter the value of Graph '))
----> 8 snap.DrawGViz(UGraph,snap.gvlCirco,"WS.png","WS small world",False)
      9 GraphClustCoeff = snap.GetClustCf(UGraph,-1)

C:\Users\julia\Anaconda2\lib\site-packages\snap.pyc in DrawGViz(tspec, *args)
 208718     if type(tspec) == PNGraph : return DrawGViz_PNGraph(tspec, *args)
 208719     if type(tspec) == PNEANet : return DrawGViz_PNEANet(tspec, *args)
---->208720     if type(tspec) == PNEANetMP : return DrawGViz_PNEANetMP(tspec, *args)
 208721     if type(tspec) == PNGraphMP: return DrawGViz_PNGraphMP(tspec, *args)
 208722     raise TypeError('First argument has invalid type')

NameError: global name 'PNEANetMP' is not defined

**Comment by roks** [comment]
The value of UGraph is overwritten. Remove this line:
UGraph = type(raw_input('enter the value of Graph '))
