### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by mattilyra** [snap-stanford/snap-python#84]
Is there any effort at the moment for supporting Python 3? What would be required for adding Python 3 support, would it be possible to create a `cython`, `cffi` , `xdress` wrapper instead of using swig?

**Comment by hhromic** [comment]
Python 2.7 is not forever either: https://docs.python.org/2/whatsnew/2.7.html#the-future-for-python-2-x

**Comment by roks** [comment]
Beta packages of snap.py for Python 3 are available here: http://snap.stanford.edu/snappy/release/beta/.

**Comment by wlmx** [comment]
> Beta packages of snap.py for Python 3 are available here: http://snap.stanford.edu/snappy/release/beta/.

No winx64 python 3 version available yet?

**Comment by ZachNew** [comment]
Are there any updates for this issue? Working with snap on a project and being restricted to python 2 is causing some big problems for us.

**Comment by fajarmf10** [comment]
Any news on py3 version?

**Comment by ZachNew** [comment]
I too would like to hear news. Thanks!

**Comment by ZachNew** [comment]
Looks like this got addressed recently. I think this issue can be closed now.

**Comment by roks** [comment]
Thanks for the reminder!
