### ISSUE TITLE
how to query a node by attribute?

### ISSUE THREAD

**Issue by gg4u** [snap-stanford/snap-python#85]
I have a multimode graph, and would like to add string attributes to nodes (such as type and _id, where _id a string) and query by the "human readable" _id:

I tried:
g.AddNode(0)

g.AddSAttrDatN(0, 'Disease', 'EFO_0000270')

but then I cannot find which method (if exist) returns you the node by querying 'EFO_0000270'.

Any help?

**Comment by roks** [comment]
In your case, 'EFO_0000270' is the attribute value. You need to create a separate hash table with a mapping from attribute values to their names, if you want to query attributes by their values rather than by their names.
